# Generated by Django 5.0 on 2023-12-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('horas_trabajadas', models.PositiveIntegerField()),
                ('pago', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
